const PARITY_NONE = '0';
const PARITY_ODD = '1';
const PARITY_EVEN = '2';

const CRLF = '1';
const CR = '2';

const LOCALSTORAGE_KEY_PORT = 'port';
const LOCALSTORAGE_KEY_BAUDRATE = 'baudrate';
const LOCALSTORAGE_KEY_DATABITS = 'databits';
const LOCALSTORAGE_KEY_PARITY = 'parity';
const LOCALSTORAGE_KEY_STOPBITS = 'stopbits';
const LOCALSTORAGE_KEY_TERMINATOR = 'terminator';

const ONE_HUNDRED_MS = 100;
const FIVE_HUNDRED_MS = 500;

module.exports = {
  PARITY_NONE,
  PARITY_ODD,
  PARITY_EVEN,
  CRLF,
  CR,
  LOCALSTORAGE_KEY_PORT,
  LOCALSTORAGE_KEY_BAUDRATE,
  LOCALSTORAGE_KEY_DATABITS,
  LOCALSTORAGE_KEY_PARITY,
  LOCALSTORAGE_KEY_STOPBITS,
  LOCALSTORAGE_KEY_TERMINATOR,
  ONE_HUNDRED_MS,
  FIVE_HUNDRED_MS
}
